### ISSUE TITLE
python 3.9 incompatibility

### ISSUE THREAD

**Issue by kendrickkay** [nrdg/fracridge#32]
It appears that on Python 3.9, fracridge indicates a requirement of scikitlearn 0.23.2...  But when trying to install scikit learn 0.23.2, I get error messages (crazy c-code compilation errors).  (Things seem to work for Python 3.8.)

Perhaps fracridge can be updated to be compatible with the latest scikit learn (0.24.2?)

**Comment by HugoSix** [comment]
I have this issue both on python 3.8 and 3.9. Any news about how to solve this ? Thank you for your help.

**Comment by arokem** [comment]
Hey @HugoSix : can you tell me how you installed fracridge? I am pretty sure these errors usually indicate some kind of issue with the installation that is not related to fracridge itself.

**Comment by HugoSix** [comment]
Hey, thank you for this quick reply !

My goal is to use GLMsingle so I tried to install it via the recommended way:
`pip install git+https://github.com/cvnlab/GLMsingle.git`
>> the error occured
I installed dependencies one by one and encountered the error again by installing fracridge with the following command : 
`pip install fracridge'

All of this was done inside conda environments (tested python 3.8 and 3.9)
I commented on this thread because it seems to happen during scikit-learn 0.23.2 installation attempt as mentioned by @kendrickkay.

**Comment by arokem** [comment]
> my current machine where I have the issue is an Apple Silicon Macbook.
Oh - that's interesting! Can you please post the full output of `pip install git+https://github.com/cvnlab/GLMsingle.git` into a clean conda env?

**Comment by HugoSix** [comment]
yes, here is the output in a txt file:
[pip_install_GLMsingle.txt](https://github.com/nrdg/fracridge/files/8713272/pip_install_GLMsingle.txt)

**Comment by arokem** [comment]
This all should be much simpler when #31 is merged. Hopefully in the next few days.

**Comment by HugoSix** [comment]
I see. Thank you for your help !
Just so you know, I managed to make everything work on my machine using this procedure : 

1. Install dependencies of fracridge and GLMsingle
2. install fracridge without dependencies
3. install GLMsingle without dependencies

At least the examples from GLMsingle are working. I will keep this post updated if I encounter any issue using the packages.

**Comment by arokem** [comment]
Should be closed by #31, but let me know if you are still seeing this issue after the pending release.
