### ISSUE TITLE
How to reverse the predicted values back to the original scale?

### ISSUE THREAD

**Issue by LiangfangLi** [nrdg/fracridge#41]
Hello everyone, thank you very much for your work. I am a newcomer who has just started exploring ridge regression. I would like to ask if it's possible to **reverse the predicted values obtained from FRR back to their original scale**? In my research, the range of the dependent variable is quite large (e.g., from 5 to 50 points). Ultimately, I want to create a scatter plot of predicted scores against actual scores, and I hope that the scale of the predicted values is consistent with the actual values. I have successfully executed the following code using Matlab; however, I have observed that the scale of the prediction scores (i.e., "pred") differs from that of the input-dependent variable "y" (i.e., "y_train"). Do you have any assistance or advice to offer regarding this issue? Thank you so much in advance.

The matlab code:

beta_tmp= fracridge(feat_train,lambda,y_train); %lambda is a set of optimal lambda values corresponding to each y variable; beta_tmp is a #feature x #lambda x #behaviors

for b = 1:size(beta_tmp,3)
    beta(:,b) = beta_tmp(:,b,b);
end

%% Predicting
pred = feat_test * beta; %pred: #sub x #behaviors

**Comment by kendrickkay** [comment]
Hi there. It is a typical feature of performing regression that the "fitted y values" are expected to have smaller range than the "actual y values". Compared to standard (non regularized) ordinary least squares estimation, ridge regression will tend to shrink the regression weights, and as a consequence will also tend to shrink the range of the fitted (or predicted) y values.  Hence, this is expected behavior.  Note that direct comparison of fitted vs. actual y values is still valid to perform.  Even though the range of the two may differ, the statistical machinery is still correct.  One way to think about this is that you don't "want" the model to output the full range of the actual data (actual y values) because some of the variance in the data is noise/unwanted variability that you do not want to fit.

**Comment by LiangfangLi** [comment]
Thank you for your detailed explanation!!! Yes, I agree that the discrepancy in scale between the predicted values and the actual values is reasonable. I have noticed that the predicted y scores obtained by FRR typically fall within the range of -1 to 1. I have been considering whether I can multiply the predicted values by the sample's standard deviation and then add the mean value back. I tested this idea, and the processed y values seem to be closer to the range of the true values. Additionally, the statistical correlations between the processed y values and the actual y values are equal to those of the original predicted values obtained from FRR.  Do you think this approach is feasible?  Thank you for your time.

**Comment by kendrickkay** [comment]
Because correlation is insensitive to scale and offset, it is expected that the correlation will not change whether or not you perform your procedure.   However, you could consider using "mean squared error" as your error metric.  This metric would indeed be highly sensitive to the application of your procedure.

"I have been considering whether I can multiply the predicted values by the sample's standard deviation and then add the mean value back." ==> While you could in theory do this, it is not clear whether you should do this. If the statistical setup is correct, then you should not "need" to perform any post-hoc adjustments. Note that assuming you are evaluating your model on some held-out data, we expect that there will be at least a small amount of "discrepancy" in the mean value. (This is simply because on held-out data, there is always going to be some sampling variability, and even the perfect model will have some discrepancy in its prediction of the mean of the held out data.) Also, note that the range of your model's prediction is correct, at least in the sense of it is what the model says it is. In other words, it is a little strange to "readjust" the output of the model. If you believe that the range output by your model is incorrect for some reason, it would seem more proper to "fix" this in the estimation (training) of your model.
